### ISSUE TITLE
 mod_ssl patch missing

### ISSUE THREAD

**Issue by JBlond** [nono303/mod_md#1]
Please add your ssl patch file to the repo.

**Comment by nono303** [comment]
Hi,
patched mod_ssl builds are on the repo. 
src are available on [2.4.x-mod_md](https://github.com/apache/httpd/tree/2.4.x-mod_md)

**Comment by nono303** [comment]
patch available here https://github.com/icing/mod_md/blob/master/patches/mod_ssl_md-2.4.x-v5.diff
