### ISSUE TITLE
Mod_md can't get certificate, but showed status say : ok

### ISSUE THREAD

**Issue by Bagu** [nono303/mod_md#4]
Hello,

I have mod_md 2.2.7 (same problem with 2.2.7) with apache 2.4.41 and fcgid 2.3.10.
I have this in status : 

`mch44.fr | mch44.fr www.mch44.fr | good | until 2020-05-14 | Let's Encrypt | on | crt.sh | Renew 2020-04-15`

`mch44.fr | d57583990ddbac80d38b302814e046fb12bb3994 | good | until 2020-02-21 | ocsp.int-x3.letsencrypt.org | Refresh 2020-02-19`

But, when i click on crt.sh, i get "Certificate not found" and the website work on http, but not on https protocol.
There is no error message, nothing else i can check, and other managed websites are ok...
What am i missing ?

**Comment by nono303** [comment]
hi @Bagu this repo is only a mod_md Windows releases deposit. You may ask it to https://github.com/icing/mod_md
