### ISSUE TITLE
Error when starting Apache 2.46-VS16, with mod_md.so version 2.40

### ISSUE THREAD

**Issue by pleo87508** [nono303/mod_md#5]
I have the mod_md.so module that is distributed with Apache Lounge httpd-2.2.46-VS16.zip.  This is running on Windows server 2019.
After downloading https://github.com/nono303/mod_md/blob/v2.4.0/vs16/x64/libcurl.dll, and https://github.com/nono303/mod_md/blob/v2.4.0/vs16/x64/mod_md.so, and replacing the mod_md.so in Apache modules folder, along with libcurl.dll, when I try and start Apache, I receive the following error:
>>> httpd.exe: Syntax error on line 140 of C:/Apache2.4.46/conf/httpd.conf: Cannot load modules/mod_md.so into server: The Apache service named is not a valid Win32 application.

Line 140 in httpd.conf is the following line:
LoadModule md_module modules/mod_md.so

**Comment by nono303** [comment]
hi @pleo87508,
Could you please put the error triggered in Windows Event Viewer?

**Comment by pleo87508** [comment]
Log Name:      Application

Source:        Apache Service

Date:          4/16/2021 9:15:19 AM

Event ID:      3299

Task Category: None

Level:         Error

Keywords:      Classic

User:          N/A

Computer:      Dataphiles001

Description:

The Apache service named  reported the following error:

>>> httpd.exe: Syntax error on line 140 of C:/Apache2.4.46/conf/httpd.conf: Cannot load modules/mod_md.so into server: The Apache service named is not a valid Win32 application.     .

Event Xml:

<Event xmlns=http://schemas.microsoft.com/win/2004/08/events/event>

  <System>

    <Provider Name="Apache Service" />

    <EventID Qualifiers="0">3299</EventID>

    <Level>2</Level>

    <Task>0</Task>

    <Keywords>0x80000000000000</Keywords>

    <TimeCreated SystemTime="2021-04-16T15:15:19.147105700Z" />

    <EventRecordID>60047</EventRecordID>

    <Channel>Application</Channel>

    <Computer>Dataphiles001</Computer>

    <Security />

  </System>

  <EventData>

    <Data>The Apache service named</Data>

    <Data>

    </Data>

    <Data>reported the following error:

&gt;&gt;&gt;</Data>

    <Data>httpd.exe: Syntax error on line 140 of C:/Apache2.4.46/conf/httpd.conf: Cannot load modules/mod_md.so into server: %1 is not a valid Win32 application.</Data>

    <Data>

    </Data>

    <Data>

    </Data>

    <Data>

    </Data>

    <Data>

    </Data>

    <Data>

    </Data>

  </EventData>

</Event>

**Comment by nono303** [comment]
> ... is not a valid **Win32** application  

Are you trying to load the x64 mod_md on httpd win32?

**Comment by pleo87508** [comment]
I don’t believe so.  I was puzzled by that as well, but I think in my original posting I show what I downloaded from ApacheLounge which is x64.  I can review again, and let you know though.

**Comment by pleo87508** [comment]
Httpd is 64 bit –

Here’s a screenshot snippet from Task Manager

**Comment by nono303** [comment]
Ok (your screenshot is not displayed...)

So, going deeper :)

1. Which version of MSVC redist x64 is installed? (might be 14.28.29910)
2. Can you check dll [Dependencies](https://github.com/lucasg/Dependencies) for httpd & mod_md
3. Can you do a [procdump](https://stackoverflow.com/questions/9016490/using-procdump-to-obtain-the-dump-of-a-service)

Once done, just attach results and I'll have a look on.

**Comment by pleo87508** [comment]
Umm, I noticed that the size of the download I was getting wasn’t close to the distributed version, and also not the same size as the sized listed at github.

Although I didn’t seem to get any notifications about anti-virus software blocking the download, and did get a file.

I think it was incomplete.  Am trying again, and will let you know the outcome.

Sorry…..

**Comment by pleo87508** [comment]
Yes, that was it.  Somehow the download was being blocked or I was only getting a partial download, but did not see any notifications.

Apologize for the trouble.

Once again thanks for providing these builds, and thanks for your patience.

Best,

Paul

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, April 18, 2021 12:44 PM
To: 'nono303/mod_md' ***@***.***>; 'nono303/mod_md' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [nono303/mod_md] Error when starting Apache 2.46-VS16, with mod_md.so version 2.40 (#5)

 

Umm, I noticed that the size of the download I was getting wasn’t close to the distributed version, and also not the same size as the sized listed at github.

Although I didn’t seem to get any notifications about anti-virus software blocking the download, and did get a file.

I think it was incomplete.  Am trying again, and will let you know the outcome.

Sorry…..

**Comment by pleo87508** [comment]
When I run md-status, I get   2.4.0-git for that version.

Closing the issue

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, April 18, 2021 12:54 PM
To: 'nono303/mod_md' ***@***.***>; 'nono303/mod_md' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [nono303/mod_md] Error when starting Apache 2.46-VS16, with mod_md.so version 2.40 (#5)

 

Yes, that was it.  Somehow the download was being blocked or I was only getting a partial download, but did not see any notifications.

Apologize for the trouble.

Once again thanks for providing these builds, and thanks for your patience.

Best,

Paul

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: Sunday, April 18, 2021 12:44 PM
To: 'nono303/mod_md' ***@***.*** ***@***.***> >; 'nono303/mod_md' ***@***.*** ***@***.***> >
Cc: 'Mention' ***@***.*** ***@***.***> >
Subject: RE: [nono303/mod_md] Error when starting Apache 2.46-VS16, with mod_md.so version 2.40 (#5)

 

Umm, I noticed that the size of the download I was getting wasn’t close to the distributed version, and also not the same size as the sized listed at github.

Although I didn’t seem to get any notifications about anti-virus software blocking the download, and did get a file.

I think it was incomplete.  Am trying again, and will let you know the outcome.

Sorry…..
